import { createActionTypes } from '../action-type-creator';

enum ITEMS_ACTIONS {
  GET_ALL = 'GET_ALL',
  GET_ONE = 'GET_ONE',
  GET_ALL_TOP_STORIES = 'GET_ALL_TOP_STORIES',
  SET_PAGE = 'SET_PAGE',
  SET_CURRENT_ITEM = 'SET_CURRENT_ITEM'
}

export const actionTypes = createActionTypes('ITEMS', [
  ITEMS_ACTIONS.GET_ALL,
  ITEMS_ACTIONS.GET_ONE,
  ITEMS_ACTIONS.GET_ALL_TOP_STORIES,
  ITEMS_ACTIONS.SET_PAGE,
  ITEMS_ACTIONS.SET_CURRENT_ITEM
]);
